sudo: false

cache:
  directories:
    - tests/elm-stuff/build-artifacts
    - sysconfcpus

install:
  - npm install -g elm@0.19.0 elm-test@0.19.0-beta5 elm-format

script:
  - elm-format --validate src tests
  - elm make --output=/dev/null
  - elm-test
